import { readFileSync } from "node:fs"

import { expect, test } from "@playwright/test"

test.describe.configure({ mode: "serial" })

test("exports a customer-ready offer as text and a real PDF", async ({ page }) => {
  await page.goto("/")
  await page.getByRole("button", { exact: true, name: "Offer" }).click()
  await expect(page.getByRole("heading", { name: "Offer draft" })).toBeVisible()
  const offerDetails = page.getByLabel("Editable offer details")
  await offerDetails.getByLabel("Offer valid until").fill("2026-07-10")
  await offerDetails.getByLabel("Offer revision note").fill("Buyer requested 10-day validity.")
  await offerDetails.getByLabel("Offer terms").fill("Payment: Net 14 days\nDelivery: FCA Helsinki")
  await offerDetails.getByLabel("Offer notes").fill("Customer-facing note for the revised offer.")
  await expect(page.getByLabel("Plain text offer")).toHaveValue(/Valid until: 2026-07-10/)
  await expect(page.getByLabel("Plain text offer")).toHaveValue(/Payment: Net 14 days/)

  const exportActions = page.getByLabel("Offer export actions")
  await expect(exportActions.getByRole("button", { name: "Copy text" })).toBeVisible()
  await expect(exportActions.getByRole("button", { name: "Download .txt" })).toBeVisible()
  await expect(exportActions.getByRole("button", { name: "Download PDF" })).toBeVisible()

  // Plain-text export downloads a non-empty .txt mirroring the offer content.
  const textDownloadPromise = page.waitForEvent("download")
  await exportActions.getByRole("button", { name: "Download .txt" }).click()
  const textDownload = await textDownloadPromise
  expect(textDownload.suggestedFilename()).toMatch(/^OFFER-\d+-rev\d+\.txt$/)
  const textPath = await textDownload.path()
  const textContent = readFileSync(textPath, "utf8")
  expect(textContent).toContain("Total excluding VAT:")
  expect(textContent).toContain("Valid until: 2026-07-10")
  expect(textContent).toContain("Payment: Net 14 days")
  expect(textContent).toContain("Customer-facing note for the revised offer.")
  await expect(page.getByLabel("Offer export history")).toContainText("Downloaded OFFER-204-rev1.txt.")

  // PDF export downloads a structurally valid PDF (real bytes, not a cosmetic label).
  const pdfDownloadPromise = page.waitForEvent("download")
  await exportActions.getByRole("button", { name: "Download PDF" }).click()
  const pdfDownload = await pdfDownloadPromise
  expect(pdfDownload.suggestedFilename()).toMatch(/^OFFER-\d+-rev\d+\.pdf$/)
  const pdfPath = await pdfDownload.path()
  const pdfBytes = readFileSync(pdfPath)
  expect(pdfBytes.byteLength).toBeGreaterThan(800)
  expect(pdfBytes.subarray(0, 7).toString("latin1")).toBe("%PDF-1.")
  expect(pdfBytes.subarray(-6).toString("latin1")).toContain("%%EOF")
  await expect(exportActions.getByText(/Saved OFFER-\d+-rev\d+\.pdf/)).toBeVisible()
  await expect(page.getByLabel("Offer export history")).toContainText("Downloaded OFFER-204-rev1.pdf (1 page).")

  await page.reload()
  await page.getByRole("button", { exact: true, name: "Offer" }).click()
  await expect(page.getByLabel("Offer export history")).toContainText("Downloaded OFFER-204-rev1.txt.")
  await expect(page.getByLabel("Offer export history")).toContainText("Downloaded OFFER-204-rev1.pdf (1 page).")
})

test("filters the RFQ queue and discloses attachments", async ({ page }) => {
  await page.goto("/")
  const queue = page.getByLabel("RFQ queue")
  await expect(queue.getByRole("button", { name: /North Forge/ })).toBeVisible()
  await expect(queue.getByRole("button", { name: /Baltic Hydraulics/ })).toBeVisible()
  await expect(queue.getByRole("button", { name: /Arctic Instruments/ })).toBeVisible()

  // The "Rush" filter is a real toggle that narrows the queue to rush RFQs.
  const rushFilter = queue.getByRole("button", { name: "Rush" })
  await rushFilter.click()
  await expect(rushFilter).toHaveAttribute("aria-pressed", "true")
  await expect(queue.getByRole("button", { name: /Baltic Hydraulics/ })).toBeVisible()
  await expect(queue.getByRole("button", { name: /North Forge/ })).toHaveCount(0)
  await expect(queue.getByRole("button", { name: /Arctic Instruments/ })).toHaveCount(0)
  await rushFilter.click()
  await expect(rushFilter).toHaveAttribute("aria-pressed", "false")
  await expect(queue.getByRole("button", { name: /North Forge/ })).toBeVisible()

  // "Open attachments" is a real disclosure of the selected RFQ's files.
  const openAttachments = page.getByRole("button", { name: "Open attachments" })
  await expect(openAttachments).toHaveAttribute("aria-expanded", "false")
  await expect(page.getByLabel("RFQ attachments")).toHaveCount(0)
  await openAttachments.click()
  await expect(openAttachments).toHaveAttribute("aria-expanded", "true")
  const attachments = page.getByLabel("RFQ attachments")
  await expect(attachments).toBeVisible()
  await expect(attachments).toContainText("FB-204-A.step")
  await expect(attachments).toContainText("FB-204-A.pdf")
})

test("runs the quote workspace costing workflow", async ({ page }) => {
  await page.goto("/")
  const queue = page.getByLabel("RFQ queue")

  await expect(page.getByRole("heading", { name: "FactoryBid OS" })).toBeVisible()
  await expect(page.getByLabel("Persistence status")).toContainText("Local fallback")
  await expect(page.getByRole("heading", { name: "CNC bracket FB-204-A" })).toBeVisible()
  await expect(page.getByLabel("Integration health")).toContainText("Fallback active")
  await expect(page.getByLabel("Integration health")).toContainText("RFQ connectors")
  await expect(page.getByLabel("Integration health")).toContainText("pending")
  await expect(page.getByLabel("RFQ calendar plan preview")).toContainText("2 drafts")
  await expect(page.getByLabel("RFQ calendar plan preview")).toContainText("Quote work: CNC bracket FB-204-A")
  await expect(page.getByLabel("RFQ calendar plan preview")).toContainText("30 Jun, 12.00 - 30 Jun, 14.00")
  await expect(page.getByLabel("RFQ calendar plan preview")).toContainText("Quote due: CNC bracket FB-204-A")
  await expect(page.getByLabel("RFQ calendar plan preview")).toContainText("30 Jun, 14.30 - 30 Jun, 15.00")
  await page.getByLabel("Integration health").getByRole("button", { name: "RFQ sync" }).click()
  await expect(page.getByLabel("Integration health")).toContainText("3 linked")
  await expect(page.getByLabel("Integration health")).toContainText("3 Gmail/calendar links attached")
  const connectorDrilldown = page.getByLabel("Connector link drill-down")
  await expect(connectorDrilldown.locator(".metric", { hasText: "Links" })).toContainText("3")
  await expect(connectorDrilldown.locator(".metric", { hasText: "Gmail" })).toContainText("1")
  await expect(connectorDrilldown.locator(".metric", { hasText: "Calendar" })).toContainText("2")
  await expect(connectorDrilldown.locator(".metric", { hasText: "Activity" })).toContainText("3")
  await expect(connectorDrilldown.getByRole("button", { name: "All 6" })).toBeVisible()
  await connectorDrilldown.getByRole("button", { name: "Gmail 1" }).click()
  await expect(connectorDrilldown).toContainText("Gmail message thread")
  await connectorDrilldown.getByRole("button", { name: "Calendar 2" }).click()
  await expect(connectorDrilldown).toContainText("Calendar event")
  await connectorDrilldown.getByRole("button", { name: "Activity 3" }).click()
  await expect(connectorDrilldown).toContainText("Synced Gmail RFQ")
  await connectorDrilldown.getByRole("button", { name: "Attention 0" }).click()
  await expect(connectorDrilldown).toContainText("No connector records match attention.")
  await connectorDrilldown.getByRole("button", { name: "All 6" }).click()
  await expect(queue.getByRole("button", { name: /Tampere Robotics/ })).toBeVisible()
  await queue.getByRole("button", { name: /Tampere Robotics/ }).click()
  await expect(page.getByRole("heading", { name: "RFQ: CNC fixture PN TR-301" })).toBeVisible()
  await page.getByRole("button", { exact: true, name: "Triage" }).click()
  await expect(page.getByLabel("RFQ intake readiness")).toContainText("Ready for costing")
  await expect(page.getByLabel("Selected RFQ")).toContainText("Imported from Gmail RFQ sync")
  await queue.getByRole("button", { name: /North Forge/ }).click()
  await expect(page.getByRole("heading", { name: "CNC bracket FB-204-A" })).toBeVisible()
  await page.getByRole("button", { exact: true, name: "Costing" }).click()
  await expect(page.getByLabel("Part preview")).toContainText("FB-204-A.step")
  await expect(page.getByLabel("Attachments", { exact: true })).toContainText("ready")
  await expect(page.getByLabel("Measurements")).toContainText("Length")
  await expect(page.getByLabel("CAD metadata")).toContainText("FB-204-A.step")
  await expect(page.getByLabel("CAD metadata")).toContainText("Aluminum 6082")
  await expect(page.getByLabel("Quote scenario comparison")).toContainText("Current edits")
  await expect(page.getByLabel("Quote scenario comparison")).toContainText("Rush expedite")
  await expect(page.getByLabel("Provider review")).toContainText("gemini")
  await expect(page.getByLabel("Provider review")).toContainText("[redacted-email]")
  await expect(page.getByLabel("Provider review")).toContainText("used mock fallback")
  const providerReview = page.getByLabel("Provider review")
  await expect(providerReview.getByLabel("Provider run history summary")).toContainText("Runs")
  await expect(providerReview.getByLabel("Provider run history summary")).toContainText("Warnings")
  await expect(providerReview.getByLabel("Provider run history filters")).toContainText("Warnings 3")
  await providerReview.getByRole("button", { name: "Failed 0" }).click()
  await expect(providerReview).toContainText("No provider runs match failed.")
  await providerReview.getByRole("button", { name: "Fallbacks 2" }).click()
  await expect(providerReview).toContainText("used mock fallback")
  await providerReview.getByRole("button", { name: "All 2" }).click()
  await expect(page.getByLabel("Process capability matrix")).toContainText("5/6 ready calculators")
  await expect(page.getByLabel("Process capability matrix")).toContainText("Wire EDM")
  await expect(page.getByLabel("Process capability matrix")).toContainText("Minimum order adjustment applied.")
  const nonCncDemos = page.getByLabel("Non-CNC registry demos")
  await expect(nonCncDemos).toContainText("Sheet metal")
  await expect(nonCncDemos.getByRole("button", { name: /Sheet metal/ })).toContainText("Best price")
  await expect(nonCncDemos.getByRole("button", { name: /Sheet metal/ })).toContainText("Fastest lead")
  await expect(nonCncDemos.getByRole("button", { name: /Sheet metal/ })).toContainText("Draft complete")
  await expect(nonCncDemos.getByRole("button", { name: /Wire EDM/ })).toContainText("4/5 inputs")
  await expect(nonCncDemos.getByRole("button", { name: /Wire EDM/ })).toContainText("Draft gaps")
  await nonCncDemos.getByRole("button", { name: /Wire EDM/ }).click()
  await expect(nonCncDemos.getByLabel("Selected non-CNC quote preview")).toContainText("EDM-KEY-077")
  await expect(nonCncDemos.getByLabel("Process quote comparison summary")).toContainText("+€5,260.69")
  await expect(nonCncDemos.getByLabel("Process quote comparison summary")).toContainText("+9d lead")
  await expect(nonCncDemos.getByLabel("Process input readiness")).toContainText("wire settings")
  await expect(nonCncDemos.getByLabel("Planned process input fields")).toContainText("Wire diameter")
  await expect(nonCncDemos.getByLabel("Read-only process input draft")).toContainText("Fixture draft 4/5")
  await expect(nonCncDemos.getByLabel("Read-only process input draft")).toContainText("Missing fixture value")
  await expect(nonCncDemos.getByLabel("Non-CNC quote path gate")).toContainText("Editable controls missing")
  await expect(nonCncDemos.getByLabel("Non-CNC quote path gate")).toContainText("Missing required values")
  await expect(nonCncDemos.getByLabel("Process quote operator checklist")).toContainText("Input model read-only")
  await expect(nonCncDemos.getByLabel("Process quote operator checklist")).toContainText("Offer wiring pending")
  await expect(nonCncDemos.getByLabel("Non-CNC promotion execution history")).toContainText("Local execution history:")
  await expect(nonCncDemos.getByLabel("Non-CNC promotion execution history")).toContainText(
    "non-cnc-quote-promotion-execution-persistence.v1",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promotion outcome draft")).toContainText(
    "non-cnc-quote-promotion-execution-outcome-draft.v1",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promotion outcome draft")).toContainText("Outcome withheld")
  await expect(nonCncDemos.getByLabel("Non-CNC promotion commit plan")).toContainText(
    "non-cnc-quote-promotion-outcome-commit.v1",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promotion commit plan")).toContainText("Outcome commit withheld")
  await expect(nonCncDemos.getByLabel("Non-CNC promotion commit history")).toContainText(
    "non-cnc-quote-promotion-outcome-commit-persistence.v1",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promotion commit history")).toContainText("Local outcome commit history:")
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application outcome draft")).toContainText(
    "non-cnc-promoted-quote-application-execution-outcome-draft.v1",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application outcome draft")).toContainText(
    "Promoted quote read model is not ready.",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application outcome draft")).toContainText("Outcome withheld")
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application commit plan")).toContainText(
    "non-cnc-promoted-quote-application-outcome-commit.v1",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application commit plan")).toContainText(
    "Application commit withheld",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application commit plan")).toContainText(
    "Application outcome draft must be ready before commit.",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application commit history")).toContainText(
    "non-cnc-promoted-quote-application-outcome-commit-persistence.v1",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application commit history")).toContainText(
    "Local application outcome commit history:",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application commit history")).toContainText(
    "Status counts: blocked 2",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application read model")).toContainText(
    "non-cnc-promoted-quote-application-outcome-commit-read-model.v1",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application read model")).toContainText("Withheld until ready")
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application read model")).toContainText(
    "active RFQ quote, offer, and release state stay unchanged",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application mutation package")).toContainText(
    "non-cnc-promoted-quote-application-mutation-package.v1",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application mutation package")).toContainText(
    "Withheld until ready",
  )
  await expect(nonCncDemos.getByLabel("Non-CNC promoted quote application mutation package")).toContainText(
    "replace active quote",
  )
  await nonCncDemos.getByRole("button", { name: "Copy summary" }).click()
  await expect(nonCncDemos.getByLabel("Process quote preview actions").getByRole("status")).toContainText(
    "Process preview summary copied.",
  )
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("5-day plan")
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("CNC milling")
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("Selected RFQ")
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("FB-204-A")
  await expect(page.getByLabel("Material availability plan")).toContainText("3 material families")
  await expect(page.getByLabel("Material availability plan")).toContainText("Aluminum 6082")
  await expect(page.getByLabel("Material availability plan")).toContainText("Stock covered")
  await expect(page.getByLabel("Material availability plan")).toContainText("Stainless Stock Oy")

  await page.getByRole("button", { name: /Baltic Hydraulics/ }).click()
  await expect(page.getByRole("heading", { name: "Turned spacer FB-TURN-019" })).toBeVisible()
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("CNC turning")
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("FB-TURN-019")
  await expect(page.getByLabel("Material availability plan")).toContainText("Stainless steel 316L")
  await expect(page.getByLabel("Material availability plan")).toContainText("Buy 3 kg by 2026-06-20")
  await expect(page.getByLabel("Material availability plan")).toContainText("Material purchase is due by 2026-06-20.")
  await expect(page.getByLabel("Outside service plan")).toContainText("1 service planned")
  await expect(page.getByLabel("Outside service plan")).toContainText("At risk")
  await expect(page.getByLabel("Outside service plan")).toContainText("Passivation")
  await expect(page.getByLabel("Outside service plan")).toContainText("Nordic Surface Works")
  await expect(page.getByLabel("Outside service plan")).toContainText("2026-06-20")
  await expect(page.getByLabel("Part preview")).toContainText("FB-TURN-019.pdf")
  await expect(page.getByText("CAD geometry is unavailable; using drawing preview.")).toBeVisible()
  await expect(page.getByLabel("Manufacturability flags")).toContainText("cad geometry missing")
  await expect(page.getByLabel("Manufacturability flags")).toContainText("metadata only review")
  await expect(page.getByLabel("Attachments", { exact: true })).toContainText("metadata only")
  await expect(page.getByLabel("CAD metadata")).toContainText("metadata fallback")
  await expect(page.getByLabel("Provider review")).toContainText("Local Codex")

  await page.getByRole("button", { exact: true, name: "Triage" }).click()
  await expect(page.getByLabel("RFQ intake readiness")).toContainText("Ready for costing")
  await expect(page.getByLabel("RFQ intake readiness").locator(".metric", { hasText: "Blockers" })).toContainText("0")
  await expect(page.getByLabel("RFQ intake readiness")).toContainText("CAD or drawing package is attached.")
  await page.getByRole("button", { name: "Move to Estimating" }).click()
  await expect(page.getByLabel("Action timeline")).toContainText("Moved RFQ from triage to estimating.")
  await page.getByRole("button", { name: "Save scenario" }).click()
  await expect(page.getByLabel("Action timeline")).toContainText("Saved quote scenario rfq-019-current-edits.")
  await page.getByRole("button", { name: "Create follow-up" }).click()
  await expect(page.getByLabel("Action timeline")).toContainText("Created offer follow-up for offer-019.")
  await expect(page.getByLabel("Integration health")).toContainText("scheduled")
  const followUpStatus = page.getByLabel("Calendar follow-up status")
  await expect(followUpStatus).toContainText("Follow-up scheduled")
  await expect(followUpStatus.locator(".metric", { hasText: "Open" })).toContainText("1")
  await expect(followUpStatus.locator(".metric", { hasText: "Completed" })).toContainText("0")
  await expect(followUpStatus.getByRole("button", { name: "Open 1" })).toBeVisible()
  await followUpStatus.getByRole("button", { name: "Open 1" }).click()
  await expect(followUpStatus).toContainText("Calendar hold due")
  await page.getByLabel("Handoff note").fill("Confirm passivation certs before sending.")
  await page.getByRole("button", { name: "Add note" }).click()
  await expect(page.getByLabel("Action timeline")).toContainText("Confirm passivation certs before sending.")

  await page.getByRole("button", { exact: true, name: "Costing" }).click()
  await page.getByLabel("Setup minutes").fill("42")
  await page.getByLabel("Cycle minutes").fill("24")
  await page.getByLabel("Material cost per kg").fill("5.50")
  await page.getByLabel("Machine hourly rate").fill("120")
  await page.getByLabel("Margin percent").fill("18.5")
  await page.getByLabel("Rush").uncheck()
  await expect(page.getByLabel("Quote scenario comparison")).toContainText("Standard lead time")
  await expect(page.getByLabel("Quote scenario comparison")).toContainText("RFQ baseline")
  await expect(page.locator(".assumption-row", { hasText: "margin percent" })).toContainText("18.5")
  await expect(page.getByText("Rush surcharge")).toHaveCount(0)
  await page.getByLabel("Material cost per kg").fill("6.40")
  await page.getByLabel("Machine hourly rate").fill("92")
  await page.getByLabel("Margin percent").fill("25")
  await expect(page.locator(".assumption-row", { hasText: "margin percent" })).toContainText("25")

  await page.getByRole("button", { exact: true, name: "Offer" }).click()
  await expect(page.getByRole("heading", { name: "Offer draft" })).toBeVisible()
  await expect(page.locator(".offer-number", { hasText: "OFFER-019" })).toBeVisible()
  await expect(page.getByLabel("Offer export package")).toContainText("PDF ready")
  await expect(page.getByLabel("Offer export package")).toContainText("OFFER-019-rev1.pdf")
  await expect(page.getByLabel("Offer alternates")).toContainText("Rush expedite option")
  await expect(page.getByLabel("Offer alternates")).toContainText("-6 days")
  await expect(page.getByLabel("Quote approval policy")).toContainText("Needs manager review")
  await expect(page.getByLabel("Quote approval policy").locator(".metric", { hasText: "Blockers" })).toContainText("0")
  await expect(page.getByLabel("Quote approval policy").locator(".metric", { hasText: "Warnings" })).toContainText("3")
  await expect(page.getByLabel("Quote approval policy")).toContainText("Calculator warnings")
  await expect(page.getByLabel("Quote approval policy")).toContainText("Payment terms")
  await expect(page.getByLabel("Quote approval policy")).toContainText("Credit limit")
  await expect(page.getByLabel("Offer send readiness")).toContainText("Needs review")
  await expect(page.getByLabel("Offer send readiness").locator(".metric", { hasText: "Blockers" })).toContainText("0")
  await expect(page.getByLabel("Offer send readiness").locator(".metric", { hasText: "Warnings" })).toContainText("1")
  await expect(page.getByLabel("Offer send readiness")).toContainText("Calculator review")
  await expect(page.getByLabel("Offer send readiness")).toContainText("Follow-up")
  await expect(page.getByLabel("Offer send readiness")).toContainText("2026-06-27")
  await expect(page.getByLabel("Quote release gate")).toContainText("Needs release review")
  await expect(page.getByLabel("Quote release gate").locator(".metric", { hasText: "Blockers" })).toContainText("0")
  await expect(page.getByLabel("Quote release gate").locator(".metric", { hasText: "Warnings" })).toContainText("4")
  await expect(page.getByLabel("Quote release gate")).toContainText("Quote approval policy needs manager review.")
  await expect(page.getByLabel("Quote release gate")).toContainText("Offer send readiness needs review.")
  await expect(page.getByLabel("Quote release gate")).toContainText("Allocated material is missing certificate paperwork.")
  await expect(page.getByLabel("Quote release gate")).toContainText("1 outside service at risk before offer release.")
  await page.getByLabel("Quote release gate").getByRole("button", { name: "Mark reviewed" }).click()
  await expect(page.getByLabel("Quote release gate")).toContainText("Reviewed by Sari")
  await expect(page.getByLabel("Quote release gate").getByRole("button", { name: "Review recorded" })).toBeDisabled()
  const offerLifecycle = page.getByRole("region", { name: "Offer lifecycle" })
  await expect(offerLifecycle).toContainText("Draft not sent")
  await expect(offerLifecycle.locator(".metric", { hasText: "Events" })).toContainText("0")
  await expect(offerLifecycle).toContainText("No lifecycle events recorded.")
  await offerLifecycle.getByRole("button", { name: "Mark sent" }).click()
  await expect(offerLifecycle).toContainText("Sent and awaiting decision")
  await expect(offerLifecycle.locator(".metric", { hasText: "Events" })).toContainText("1")
  await expect(offerLifecycle).toContainText("Sent customer-ready offer OFFER-019.")
  await offerLifecycle.getByRole("button", { name: "Schedule follow-up" }).click()
  await expect(offerLifecycle).toContainText("Follow-up scheduled")
  await expect(offerLifecycle.locator(".metric", { hasText: "Open follow-ups" })).toContainText("1")
  await expect(offerLifecycle.getByRole("button", { name: "Schedule follow-up" })).toBeDisabled()
  await offerLifecycle.getByRole("button", { name: "Complete follow-up" }).click()
  await expect(offerLifecycle).toContainText("Follow-up completed")
  await expect(offerLifecycle.locator(".metric", { hasText: "Open follow-ups" })).toContainText("0")
  await offerLifecycle.getByRole("button", { name: "Mark accepted" }).click()
  await expect(offerLifecycle).toContainText("Offer accepted")
  await expect(offerLifecycle.locator(".metric", { hasText: "Events" })).toContainText("4")
  await expect(offerLifecycle.getByRole("button", { name: "Complete follow-up" })).toBeDisabled()
  await expect(offerLifecycle.getByRole("button", { name: "Mark declined" })).toBeDisabled()
  await expect(page.getByLabel("Offer release command plan")).toContainText("Blocked before release")
  await expect(page.getByLabel("Offer release command plan").locator(".metric", { hasText: "Mode" })).toContainText("blocked")
  await expect(page.getByLabel("Offer release command plan").locator(".metric", { hasText: "Commands" })).toContainText("1")
  await expect(page.getByLabel("Offer release command plan").locator(".metric", { hasText: "Follow-ups" })).toContainText("0")
  await expect(page.getByLabel("Offer release command plan")).toContainText("Resolve release blockers")
  await expect(page.getByLabel("Offer release command plan")).toContainText(
    "RFQ status must be ready before offer release; current status is estimating.",
  )
  await expect(page.getByLabel("Offer release execution audit")).toContainText("Blocked before execution")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Mode" })).toContainText("dry run")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Commands" })).toContainText("1")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Artifacts" })).toContainText("0")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Warnings" })).toContainText("0")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Fingerprint" })).toContainText(
    /^\s*Fingerprint\s*[a-f0-9]{8}\s*$/i,
  )
  await expect(page.getByLabel("Offer release execution audit")).toContainText("Resolve release blockers")
  await expect(page.getByLabel("Offer release execution history")).toContainText("1 recorded run")
  await expect(page.getByLabel("Offer release execution history").locator(".metric", { hasText: "Runs" })).toContainText(
    "1",
  )
  await expect(
    page.getByLabel("Offer release execution history").locator(".metric", { hasText: "Latest" }),
  ).toContainText("blocked")
  await expect(
    page.getByLabel("Offer release execution history").locator(".metric", { hasText: "Retries" }),
  ).toContainText("0")
  await expect(
    page.getByLabel("Offer release execution history").locator(".metric", { hasText: "Actions" }),
  ).toContainText("5")
  await expect(page.getByLabel("Offer release execution history")).toContainText("No repeated release fingerprints.")
  await page.getByRole("button", { name: "Sync replies" }).click()
  await expect(page.getByLabel("Offer reply sync")).toContainText("2 matched reply signals")
  await expect(page.getByLabel("Integration health")).toContainText("2 fallback")
  await expect(page.getByLabel("Offer reply sync")).toContainText("fallback")
  const offerReplyState = page.getByLabel("Offer reply state", { exact: true })
  await expect(offerReplyState).toContainText("Recorded")
  await expect(offerReplyState).toContainText("2")
  await expect(page.getByLabel("Offer reply sync")).toContainText("accepted")
  await expect(page.getByLabel("Offer reply sync")).toContainText("follow up completed")
  await offerReplyState.getByRole("button", { name: "Warnings", exact: true }).click()
  await expect(offerReplyState).toContainText("Used mock offer reply fallback.")
  await offerReplyState.getByRole("button", { name: "Transitions", exact: true }).click()
  await expect(offerReplyState).toContainText("accepted")
  await expect(page.getByLabel("Integration health")).toContainText("2 matched reply signals from fallback search")
  await expect(page.getByLabel("Integration health")).toContainText("Follow-up hold scheduled")
  await page.getByRole("button", { exact: true, name: "Triage" }).click()
  await expect(page.getByLabel("Calendar follow-up status")).toContainText("Follow-up completed")
  await expect(page.getByLabel("Calendar follow-up status").locator(".metric", { hasText: "Completed" })).toContainText(
    "1",
  )
  await page.getByLabel("Calendar follow-up status").getByRole("button", { name: "Completed 1" }).click()
  await expect(page.getByLabel("Calendar follow-up status")).toContainText("Completed")
  await page.getByRole("button", { exact: true, name: "Offer" }).click()
  await expect(page.getByLabel("Plain text offer")).toHaveValue(/Total excluding VAT: EUR 500\.00/)
})

test("executes a reviewed release plan through the local adapter", async ({ page }) => {
  await page.goto("/")
  await page.getByRole("button", { exact: true, name: "Offer" }).click()

  await page.getByLabel("Quote release gate").getByRole("button", { name: "Mark reviewed" }).click()
  await expect(page.getByLabel("Quote release gate")).toContainText("Reviewed by Sari")

  await page.getByRole("button", { exact: true, name: "Triage" }).click()
  await page.getByRole("button", { name: "Create follow-up" }).click()
  await page.getByRole("button", { name: "Move to ready" }).click()
  await page.getByRole("button", { exact: true, name: "Offer" }).click()

  await expect(page.getByLabel("Offer release command plan")).toContainText("Release commands ready")
  await expect(page.getByLabel("Offer release calendar drafts")).toContainText("Follow up: OFFER-204")
  await expect(page.getByLabel("Offer release calendar drafts")).toContainText("03 Jul, 10.00 - 03 Jul, 10.30")
  await expect(page.getByLabel("Offer release calendar drafts")).toContainText("Europe/Helsinki")
  await expect(page.getByLabel("Offer release execution audit")).toContainText("Dry-run prepared")
  await page.getByLabel("Offer release execution audit").getByRole("button", { name: "Execute release" }).click()
  await expect(page.getByLabel("Offer release execution audit")).toContainText("Execution completed")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Mode" })).toContainText("commit")
  await expect(page.getByLabel("Offer release execution audit")).toContainText(
    "Local adapter recorded the command; no external connector call was made.",
  )
  await expect(page.getByLabel("Offer release execution audit").getByRole("button", { name: "Release executed" })).toBeDisabled()
  await expect(page.getByLabel("Offer release execution history")).toContainText("2 recorded runs")

  await page.reload()
  await page.getByRole("button", { exact: true, name: "Offer" }).click()
  await expect(page.getByLabel("Offer release execution audit")).toContainText("Execution completed")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Mode" })).toContainText("commit")
  await expect(page.getByLabel("Offer release execution history")).toContainText("2 recorded runs")
})
