import { expect, test } from "@playwright/test"

test("runs the quote workspace costing workflow", async ({ page }) => {
  await page.goto("/")

  await expect(page.getByRole("heading", { name: "FactoryBid OS" })).toBeVisible()
  await expect(page.getByLabel("Persistence status")).toContainText("Local fallback")
  await expect(page.getByRole("heading", { name: "CNC bracket FB-204-A" })).toBeVisible()
  await expect(page.getByLabel("Integration health")).toContainText("Fallback active")
  await expect(page.getByLabel("Integration health")).toContainText("RFQ connectors")
  await expect(page.getByLabel("Integration health")).toContainText("pending")
  await page.getByLabel("Integration health").getByRole("button", { name: "RFQ sync" }).click()
  await expect(page.getByLabel("Integration health")).toContainText("3 stale")
  await expect(page.getByLabel("Integration health")).toContainText("3 connector links stale")
  const connectorDrilldown = page.getByLabel("Connector link drill-down")
  await expect(connectorDrilldown.locator(".metric", { hasText: "Links" })).toContainText("3")
  await expect(connectorDrilldown.locator(".metric", { hasText: "Gmail" })).toContainText("1")
  await expect(connectorDrilldown.locator(".metric", { hasText: "Calendar" })).toContainText("2")
  await expect(connectorDrilldown.locator(".metric", { hasText: "Activity" })).toContainText("3")
  await expect(connectorDrilldown.getByRole("button", { name: "All 6" })).toBeVisible()
  await connectorDrilldown.getByRole("button", { name: "Gmail 1" }).click()
  await expect(connectorDrilldown).toContainText("Gmail message thread")
  await connectorDrilldown.getByRole("button", { name: "Calendar 2" }).click()
  await expect(connectorDrilldown).toContainText("Calendar event")
  await connectorDrilldown.getByRole("button", { name: "Activity 3" }).click()
  await expect(connectorDrilldown).toContainText("Synced Gmail RFQ")
  await connectorDrilldown.getByRole("button", { name: "Attention 3" }).click()
  await expect(connectorDrilldown).toContainText("stale")
  await connectorDrilldown.getByRole("button", { name: "All 6" }).click()
  await expect(page.getByLabel("Part preview")).toContainText("FB-204-A.step")
  await expect(page.getByLabel("Attachments", { exact: true })).toContainText("ready")
  await expect(page.getByLabel("Measurements")).toContainText("Length")
  await expect(page.getByLabel("CAD metadata")).toContainText("FB-204-A.step")
  await expect(page.getByLabel("CAD metadata")).toContainText("Aluminum 6082")
  await expect(page.getByLabel("Quote scenario comparison")).toContainText("Current edits")
  await expect(page.getByLabel("Quote scenario comparison")).toContainText("Rush expedite")
  await expect(page.getByLabel("Provider review")).toContainText("gemini")
  await expect(page.getByLabel("Provider review")).toContainText("[redacted-email]")
  await expect(page.getByLabel("Provider review")).toContainText("used mock fallback")
  const providerReview = page.getByLabel("Provider review")
  await expect(providerReview.getByLabel("Provider run history summary")).toContainText("Runs")
  await expect(providerReview.getByLabel("Provider run history summary")).toContainText("Warnings")
  await expect(providerReview.getByLabel("Provider run history filters")).toContainText("Warnings 3")
  await providerReview.getByRole("button", { name: "Failed 0" }).click()
  await expect(providerReview).toContainText("No provider runs match failed.")
  await providerReview.getByRole("button", { name: "Fallbacks 2" }).click()
  await expect(providerReview).toContainText("used mock fallback")
  await providerReview.getByRole("button", { name: "All 2" }).click()
  await expect(page.getByLabel("Process capability matrix")).toContainText("5/6 ready calculators")
  await expect(page.getByLabel("Process capability matrix")).toContainText("Wire EDM")
  await expect(page.getByLabel("Process capability matrix")).toContainText("Minimum order adjustment applied.")
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("5-day plan")
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("CNC milling")
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("Selected RFQ")
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("FB-204-A")
  await expect(page.getByLabel("Material availability plan")).toContainText("3 material families")
  await expect(page.getByLabel("Material availability plan")).toContainText("Aluminum 6082")
  await expect(page.getByLabel("Material availability plan")).toContainText("Stock covered")
  await expect(page.getByLabel("Material availability plan")).toContainText("Stainless Stock Oy")

  await page.getByRole("button", { name: /Baltic Hydraulics/ }).click()
  await expect(page.getByRole("heading", { name: "Turned spacer FB-TURN-019" })).toBeVisible()
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("CNC turning")
  await expect(page.getByLabel("Capacity commitment plan")).toContainText("FB-TURN-019")
  await expect(page.getByLabel("Material availability plan")).toContainText("Stainless steel 316L")
  await expect(page.getByLabel("Material availability plan")).toContainText("Buy 3 kg by 2026-06-20")
  await expect(page.getByLabel("Material availability plan")).toContainText("Material purchase is due by 2026-06-20.")
  await expect(page.getByLabel("Outside service plan")).toContainText("1 service planned")
  await expect(page.getByLabel("Outside service plan")).toContainText("At risk")
  await expect(page.getByLabel("Outside service plan")).toContainText("Passivation")
  await expect(page.getByLabel("Outside service plan")).toContainText("Nordic Surface Works")
  await expect(page.getByLabel("Outside service plan")).toContainText("2026-06-20")
  await expect(page.getByLabel("Part preview")).toContainText("FB-TURN-019.pdf")
  await expect(page.getByText("CAD geometry is unavailable; using drawing preview.")).toBeVisible()
  await expect(page.getByLabel("Manufacturability flags")).toContainText("cad geometry missing")
  await expect(page.getByLabel("Manufacturability flags")).toContainText("metadata only review")
  await expect(page.getByLabel("Attachments", { exact: true })).toContainText("metadata only")
  await expect(page.getByLabel("CAD metadata")).toContainText("metadata fallback")
  await expect(page.getByLabel("Provider review")).toContainText("Local Codex")

  await page.getByRole("button", { exact: true, name: "Triage" }).click()
  await expect(page.getByLabel("RFQ intake readiness")).toContainText("Ready for costing")
  await expect(page.getByLabel("RFQ intake readiness").locator(".metric", { hasText: "Blockers" })).toContainText("0")
  await expect(page.getByLabel("RFQ intake readiness")).toContainText("CAD or drawing package is attached.")
  await page.getByRole("button", { name: "Move to Estimating" }).click()
  await expect(page.getByLabel("Action timeline")).toContainText("Moved RFQ from triage to estimating.")
  await page.getByRole("button", { name: "Save scenario" }).click()
  await expect(page.getByLabel("Action timeline")).toContainText("Saved quote scenario rfq-019-current-edits.")
  await page.getByRole("button", { name: "Create follow-up" }).click()
  await expect(page.getByLabel("Action timeline")).toContainText("Created offer follow-up for offer-019.")
  await expect(page.getByLabel("Integration health")).toContainText("scheduled")
  const followUpStatus = page.getByLabel("Calendar follow-up status")
  await expect(followUpStatus).toContainText("Follow-up scheduled")
  await expect(followUpStatus.locator(".metric", { hasText: "Open" })).toContainText("1")
  await expect(followUpStatus.locator(".metric", { hasText: "Completed" })).toContainText("0")
  await expect(followUpStatus.getByRole("button", { name: "Open 1" })).toBeVisible()
  await followUpStatus.getByRole("button", { name: "Open 1" }).click()
  await expect(followUpStatus).toContainText("Calendar hold due")
  await page.getByLabel("Handoff note").fill("Confirm passivation certs before sending.")
  await page.getByRole("button", { name: "Add note" }).click()
  await expect(page.getByLabel("Action timeline")).toContainText("Confirm passivation certs before sending.")

  await page.getByRole("button", { exact: true, name: "Costing" }).click()
  await page.getByLabel("Setup minutes").fill("42")
  await page.getByLabel("Cycle minutes").fill("24")
  await page.getByLabel("Rush").uncheck()
  await expect(page.getByLabel("Quote scenario comparison")).toContainText("Standard lead time")
  await expect(page.getByLabel("Quote scenario comparison")).toContainText("RFQ baseline")
  await expect(page.getByText("Rush surcharge")).toHaveCount(0)

  await page.getByRole("button", { exact: true, name: "Offer" }).click()
  await expect(page.getByRole("heading", { name: "Offer draft" })).toBeVisible()
  await expect(page.locator(".offer-number", { hasText: "OFFER-019" })).toBeVisible()
  await expect(page.getByLabel("Offer export package")).toContainText("PDF ready")
  await expect(page.getByLabel("Offer export package")).toContainText("OFFER-019-rev1.pdf")
  await expect(page.getByLabel("Offer alternates")).toContainText("Rush expedite option")
  await expect(page.getByLabel("Offer alternates")).toContainText("-6 days")
  await expect(page.getByLabel("Quote approval policy")).toContainText("Needs manager review")
  await expect(page.getByLabel("Quote approval policy").locator(".metric", { hasText: "Blockers" })).toContainText("0")
  await expect(page.getByLabel("Quote approval policy").locator(".metric", { hasText: "Warnings" })).toContainText("3")
  await expect(page.getByLabel("Quote approval policy")).toContainText("Calculator warnings")
  await expect(page.getByLabel("Quote approval policy")).toContainText("Payment terms")
  await expect(page.getByLabel("Quote approval policy")).toContainText("Credit limit")
  await expect(page.getByLabel("Offer send readiness")).toContainText("Needs review")
  await expect(page.getByLabel("Offer send readiness").locator(".metric", { hasText: "Blockers" })).toContainText("0")
  await expect(page.getByLabel("Offer send readiness").locator(".metric", { hasText: "Warnings" })).toContainText("1")
  await expect(page.getByLabel("Offer send readiness")).toContainText("Calculator review")
  await expect(page.getByLabel("Offer send readiness")).toContainText("Follow-up")
  await expect(page.getByLabel("Offer send readiness")).toContainText("2026-06-27")
  await expect(page.getByLabel("Quote release gate")).toContainText("Needs release review")
  await expect(page.getByLabel("Quote release gate").locator(".metric", { hasText: "Blockers" })).toContainText("0")
  await expect(page.getByLabel("Quote release gate").locator(".metric", { hasText: "Warnings" })).toContainText("4")
  await expect(page.getByLabel("Quote release gate")).toContainText("Quote approval policy needs manager review.")
  await expect(page.getByLabel("Quote release gate")).toContainText("Offer send readiness needs review.")
  await expect(page.getByLabel("Quote release gate")).toContainText("Allocated material is missing certificate paperwork.")
  await expect(page.getByLabel("Quote release gate")).toContainText("1 outside service at risk before offer release.")
  await expect(page.getByLabel("Offer release command plan")).toContainText("Blocked before release")
  await expect(page.getByLabel("Offer release command plan").locator(".metric", { hasText: "Mode" })).toContainText("blocked")
  await expect(page.getByLabel("Offer release command plan").locator(".metric", { hasText: "Commands" })).toContainText("1")
  await expect(page.getByLabel("Offer release command plan").locator(".metric", { hasText: "Follow-ups" })).toContainText("0")
  await expect(page.getByLabel("Offer release command plan")).toContainText("Resolve release blockers")
  await expect(page.getByLabel("Offer release command plan")).toContainText(
    "RFQ status must be ready before offer release; current status is estimating.",
  )
  await expect(page.getByLabel("Offer release execution audit")).toContainText("Blocked before execution")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Mode" })).toContainText("dry run")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Commands" })).toContainText("1")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Artifacts" })).toContainText("0")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Warnings" })).toContainText("0")
  await expect(page.getByLabel("Offer release execution audit").locator(".metric", { hasText: "Fingerprint" })).toContainText(
    /^\s*Fingerprint\s*[a-f0-9]{8}\s*$/i,
  )
  await expect(page.getByLabel("Offer release execution audit")).toContainText("Resolve release blockers")
  await expect(page.getByLabel("Offer release execution history")).toContainText("1 recorded run")
  await expect(page.getByLabel("Offer release execution history").locator(".metric", { hasText: "Runs" })).toContainText(
    "1",
  )
  await expect(
    page.getByLabel("Offer release execution history").locator(".metric", { hasText: "Latest" }),
  ).toContainText("blocked")
  await expect(
    page.getByLabel("Offer release execution history").locator(".metric", { hasText: "Retries" }),
  ).toContainText("0")
  await expect(
    page.getByLabel("Offer release execution history").locator(".metric", { hasText: "Actions" }),
  ).toContainText("5")
  await expect(page.getByLabel("Offer release execution history")).toContainText("No repeated release fingerprints.")
  await page.getByRole("button", { name: "Sync replies" }).click()
  await expect(page.getByLabel("Offer reply sync")).toContainText("2 matched reply signals")
  await expect(page.getByLabel("Integration health")).toContainText("2 fallback")
  await expect(page.getByLabel("Offer reply sync")).toContainText("fallback")
  const offerReplyState = page.getByLabel("Offer reply state", { exact: true })
  await expect(offerReplyState).toContainText("Recorded")
  await expect(offerReplyState).toContainText("2")
  await expect(page.getByLabel("Offer reply sync")).toContainText("accepted")
  await expect(page.getByLabel("Offer reply sync")).toContainText("follow up completed")
  await offerReplyState.getByRole("button", { name: "Warnings", exact: true }).click()
  await expect(offerReplyState).toContainText("Used mock offer reply fallback.")
  await offerReplyState.getByRole("button", { name: "Transitions", exact: true }).click()
  await expect(offerReplyState).toContainText("accepted")
  await expect(page.getByLabel("Integration health")).toContainText("2 matched reply signals from fallback search")
  await expect(page.getByLabel("Integration health")).toContainText("Follow-up hold scheduled")
  await page.getByRole("button", { exact: true, name: "Triage" }).click()
  await expect(page.getByLabel("Calendar follow-up status")).toContainText("Follow-up completed")
  await expect(page.getByLabel("Calendar follow-up status").locator(".metric", { hasText: "Completed" })).toContainText(
    "1",
  )
  await page.getByLabel("Calendar follow-up status").getByRole("button", { name: "Completed 1" }).click()
  await expect(page.getByLabel("Calendar follow-up status")).toContainText("Completed")
  await page.getByRole("button", { exact: true, name: "Offer" }).click()
  await expect(page.getByLabel("Plain text offer")).toHaveValue(/Total excluding VAT: EUR 500\.00/)
})
